---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS CloudFormation Sample Template S3_Website_Bucket_With_Retain_On_Delete:
  Sample template showing how to create a publicly accessible S3 bucket configured
  for website access with a deletion policy of retain on delete. **WARNING** This
  template creates an S3 bucket that will NOT be deleted when the stack is deleted.
  You will be billed for the AWS resources used if you create a stack from this template.'

Parameters:
  Environment:
    Description: Environment name to provision resources
    Type: String
    AllowedValues: ["dev", "prod"]
    Default: dev

Mappings: 
  BucketName: 
    dev: 
      Name: "simple-sinatra-infra-dev"
    prod: 
      Name: "simple-sinatra-infra-prod"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap
        - BucketName
        - !Ref Environment
        - Name
      AccessControl: Private
      Tags: 
        - Key: "project"
          Value: "simple-sinatra-infra"
        - Key: "createby"
          Value: "fen9li cloudformation stacks"
        - Key: "chargeto"
          Value: !Ref Environment
    DeletionPolicy: Delete

Outputs:
  S3BucketSecureURL:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Fn::GetAtt:
          - S3Bucket
          - DomainName
    Description: S3 bucket secure url
