---
AWSTemplateFormatVersion: '2010-09-09'
Description: simple sinatra app infrastructure stack
Parameters:
  env:
    Description: Environment name to provision resources
    Type: String
    AllowedValues: ["dev", "prod"]
    Default: dev

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        env: !Ref env
      TemplateURL: http://simple-sinatra-app-infrastructure.s3.amazonaws.com/nested/vpc.yaml
      TimeoutInMinutes: '5'

Outputs:
  VpcId:
    Description: The ID of the VPC that this stack is deployed in
    Value: !GetAtt VpcStack.Outputs.VpcId
